### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by eugeniodilo** [marcsosduma/cobgdb#14]
When you type the Q (Quit) command the debugger send a message where is COBGBD instead of COBGDB.
See image: 

![image](https://github.com/marcsosduma/cobgdb/assets/13390725/321c850d-c625-4850-b4f7-3670f8acf6a2)

**Comment by marcsosduma** [comment]
Oops! I'll fix that... thank you.

**Comment by eugeniodilo** [comment]
Fixed
