### ISSUE TITLE
Help message of B command

### ISSUE THREAD

**Issue by eugeniodilo** [marcsosduma/cobgdb#16]
Into the file variables.c  at line 883 is specified:         `"B - Sets a breakpoint at a specific point in the code."`,

I think it should be changed to:         `"B - Sets or Unsets a breakpoint at a specific point in the code."`,

**Comment by GitMensch** [comment]
Or much better: `B - Toggles the breakpoint at the current selected line.`.

@eugeniodilo: What do you think about suggesting the change? Just open the global source editing by pressing a `.`, then adjust this source file and README (automatically saved within your browser) then switch from the Explorer View (1) to the VSC view (2), enter a message what this is about then commit and push (3), then enter a reasonable short name [that's only temporary]) and follow the UI to create a Pull-Request
![grafik](https://github.com/marcsosduma/cobgdb/assets/6699539/1a721362-ce67-4c38-8329-712e8a1c9851)

**Comment by GitMensch** [comment]
Fixed with 34da0286c8047cf8d36a5095971a890f3d86d7a2, should be closed.

**Comment by eugeniodilo** [comment]
fixed
