### ISSUE TITLE
problems in compiling example "Unable to open file!"

### ISSUE THREAD

**Issue by GitMensch** [marcsosduma/cobgdb#18]
On a clean Ubuntu 22.04:

```
~ $ sudo apt install -y gnucobol
~ $ mkdir /workspace
~ $ cd /workspace
/workspace $ git glone https://github.com/marcsosduma/cobgdb
/workspace $ cd cobgdb
/workspace/cobgdb (main) $ make
/workspace/cobgdb (main) $ ./cobgdb resources/datatypes.cbl -fixed
Name: resources/datatypes
cobc -g -fsource-location -ftraceall -v -free -O0 -x -fixed resources/datatypes.cbl 
loading standard configuration file 'default.conf'
command line:   cobc -g -fsource-location -ftraceall -v -free -O0 -x -fixed resources/datatypes.cbl 
preprocessing:  resources/datatypes.cbl -> datatypes.i
return status:  0
parsing:        datatypes.i (resources/datatypes.cbl)
resources/datatypes.cbl:45: warning: USAGE BIT is not implemented [-Wpending]
resources/datatypes.cbl:58: warning: handling of USAGE NATIONAL is unfinished; implementation is likely to be changed [-Wunfinished]
resources/datatypes.cbl:59: warning: handling of USAGE NATIONAL is unfinished; implementation is likely to be changed [-Wunfinished]
resources/datatypes.cbl:60: warning: handling of USAGE NATIONAL is unfinished; implementation is likely to be changed [-Wunfinished]
resources/datatypes.cbl:61: warning: handling of USAGE NATIONAL is unfinished; implementation is likely to be changed [-Wunfinished]
resources/datatypes.cbl:62: warning: handling of USAGE NATIONAL is unfinished; implementation is likely to be changed [-Wunfinished]
resources/datatypes.cbl:63: warning: handling of USAGE NATIONAL is unfinished; implementation is likely to be changed [-Wunfinished]
return status:  0
translating:    datatypes.i -> datatypes.c (resources/datatypes.cbl)
executing:      gcc -c -finline-functions -D_FORTIFY_SOURCE=2 -ggdb3 -pipe
                -Wdate-time -D_FORTIFY_SOURCE=2 -Wno-unused -fsigned-char
                -Wno-pointer-sign -ggdb3 -fasynchronous-unwind-tables -O0 -o
                "/tmp/cob1941_0.o" "datatypes.c"
return status:  0
executing:      gcc -Wl,--export-dynamic -o "datatypes" "/tmp/cob1941_0.o"
                -Wl,-Bsymbolic-functions -flto=auto -Wl,-z,relro
                -L/usr/lib/x86_64-linux-gnu -lcob -lm
return status:  0
cobc (GnuCOBOL) 3.1.2.0
Built     Sep 14 2021 19:23:38  Packaged  Dec 23 2020 12:04:58 UTC
C version "11.2.0"
Parser starting...
Parser end...
Unable to open file!: No such file or directory
```

**Comment by marcsosduma** [comment]
Hi Simon! I think it has been resolved. Thank you.

**Comment by GitMensch** [comment]
Rechecked, that works fine now.

Just an interesting note: while the mouse part don't work (I'm not sure it could), cobgdb also works within a running vscode terminal on GNU/Linux (defaulting to `TERM=xterm-256color`)

**Comment by marcsosduma** [comment]
Yes. It works... I tested several times using this configuration:
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch",
            "type": "cppdbg",
            "request": "launch",
            "preLaunchTask": "C/C++: gcc.exe build active file",
            "externalConsole": true,
            //"program": "${workspaceFolder}/${fileBasenameNoExtension}.exe",
            "windows": {
                "program": "${workspaceFolder}/cobgdb.exe",
                //"args": [ "dumamenuex.cob", "dumamenu.cob", "-lpdcurses" ],
                //"args": ["--test"],
                //"args": [ "sample.cbl", "subsample.cbl", "subsubsample.cbl" ],
                //"args": [ "number.cob" ],
                "args": ["cobol_source\\customer.cob"],
                //"args": ["simple.cob"],
                //"args": ["datatypes.cob"],
            },
            "linux": {
                "program": "${workspaceFolder}/cobgdb",
                //"args": [ "dumamenuex.cob", "dumamenu.cob", "-lncursesw" ],
                //"args": ["--test"],
                //"args": [ "sample.cbl", "subsample.cbl", "subsubsample.cbl" ],
                //"args": [ "number.cob" ],
                //"args": ["cobol_source/customer.cob"],
                //"args": ["simple.cob"],
                "args": ["datatypes.cob"],
            },
            "environment": [{ "name": "config", "value": "Debug" }],
            "cwd": "${workspaceFolder}"
        },
        {
            "name": "C++ Launch - terminal local",
            "type": "cppdbg",
            "request": "launch",
            "preLaunchTask": "C/C++: gcc.exe build active file",
            "externalConsole": false,
            //"program": "${workspaceFolder}/${fileBasenameNoExtension}.exe",
            "windows": {
                "program": "${workspaceFolder}/cobgdb.exe",
                "args": [ "dumamenuex.cob", "dumamenu.cob", "-lpdcurses" ],
                //"args": ["--test"],
                //"args": [ "sample.cbl", "subsample.cbl", "subsubsample.cbl" ],
                //"args": [ "number.cob" ],
                //"args": ["customer.cob"],
                //"args": ["simple.cob"],
            },
            "linux": {
                "program": "${workspaceFolder}/cobgdb",
                "args": [ "dumamenuex.cob", "dumamenu.cob", "-lncursesw" ],
                //"args": ["--test"],
                //"args": [ "sample.cbl", "subsample.cbl", "subsubsample.cbl" ],
                //"args": [ "number.cob" ],
                //"args": ["customer.cob"],
                //"args": ["simple.cob"],
            },
            "environment": [{ "name": "config", "value": "Debug" }],
            "cwd": "${workspaceFolder}"
        }        
    ]
}

**Comment by marcsosduma** [comment]
This part:
{
            "name": "C++ Launch - terminal local",
            "type": "cppdbg",
            "request": "launch",
            "preLaunchTask": "C/C++: gcc.exe build active file",
            "externalConsole": false,
            //"program": "${workspaceFolder}/${fileBasenameNoExtension}.exe",
            "windows": {
                "program": "${workspaceFolder}/cobgdb.exe",
                "args": [ "dumamenuex.cob", "dumamenu.cob", "-lpdcurses" ],
                //"args": ["--test"],
                //"args": [ "sample.cbl", "subsample.cbl", "subsubsample.cbl" ],
                //"args": [ "number.cob" ],
                //"args": ["customer.cob"],
                //"args": ["simple.cob"],
            },
            "linux": {
                "program": "${workspaceFolder}/cobgdb",
                "args": [ "dumamenuex.cob", "dumamenu.cob", "-lncursesw" ],
                //"args": ["--test"],
                //"args": [ "sample.cbl", "subsample.cbl", "subsubsample.cbl" ],
                //"args": [ "number.cob" ],
                //"args": ["customer.cob"],
                //"args": ["simple.cob"],
            },
            "environment": [{ "name": "config", "value": "Debug" }],
            "cwd": "${workspaceFolder}"
        }
