### ISSUE TITLE
FR: add tooltip to debugging symbols

### ISSUE THREAD

**Issue by eugeniodilo** [marcsosduma/cobgdb#24]
you've added some symbols to the top right of the debugger screen (some arrows and others).
I think it would be useful to have a tooltip so that by hovering the mouse over the symbol then the debugger indicates which command is associated with each symbol.

**Comment by eugeniodilo** [comment]
a tooltip in a textual environment can be a simple string of text (perhaps surrounded by a small box) that appears when I hover the mouse over a certain symbol.

**Comment by eugeniodilo** [comment]
I just saw that by passing the mouse over one of the symbols at the top right of the screen, the description of a command appears at the bottom left of the screen.
This already helps but the commands displayed are different from the commands described in the HELP window.
see the screenshot I attach, a "step into" command is displayed at the bottom left which does not exist in the help window.
It would be good to have the same description that appears in the help window. what do you think ?
![Step-Into](https://github.com/marcsosduma/cobgdb/assets/13390725/eab07785-61be-4406-b321-9b934c0d8abc)

**Comment by marcsosduma** [comment]
Hello Prof. Eugenio! I'll see what I can do. Any suggestions?

**Comment by eugeniodilo** [comment]
I would say that you should simply display the description of the corresponding command at the bottom left.
But this description must match one of the commands in the HELP: 

? | Help
B | Breakpoint
R | Run
C | Cursor
N | Next
S | Step
G | Go
V | Variables
H | sHow
F | File
A | Attach
Q | Quit

"Step Into" and "Step Over" are displayed but they are not present in the help
For example, "Stop" is now displayed when "Quit" should be displayed.

**Comment by marcsosduma** [comment]
Hello! I tried to adjust the 'help'...

**Comment by eugeniodilo** [comment]
Good job ! I  close this issue
