### ISSUE TITLE
FR: display variable fields time too short

### ISSUE THREAD

**Issue by eugeniodilo** [marcsosduma/cobgdb#25]
Command H or right click displays variable content on screen.
the window disappears automatically after a few seconds
![H-Screen](https://github.com/marcsosduma/cobgdb/assets/13390725/f92a7206-cdf2-478d-a655-1c7696aaca8a)

When the variables displayed are quite complex (for example see the attached screenshot) this time is too short, it is not enough to analyze the contents of the variables in the window.
I suggest making the window disappear only with another right click at the user's discretion.
This time could however be configured in a variable to be set in a configuration file called cobgdb.cfg (for example with the same logic as the runtime.cfg file of the GnuCOBOL compiler)

**Comment by GitMensch** [comment]
In both cases I vote to *only* close if SPACE or ESC are pressed

**Comment by marcsosduma** [comment]
Olá! Ok. I will make that change.

**Comment by eugeniodilo** [comment]
good job also for this issue.
now if you click on a variable with right mouse key the H command (show variable content) is executed and a pop-up window appears.
to close this pop-up window  now we have to left click ... it is good but it should be more comfortable to close the window with another right clik. what do you think ?

**Comment by marcsosduma** [comment]
Hello Prof. Eugenio! It's now possible to close the window with a right-click (equivalent to the ENTER key).

**Comment by eugeniodilo** [comment]
Good. I can close this issue
