### ISSUE TITLE
FILE command

### ISSUE THREAD

**Issue by eugeniodilo** [marcsosduma/cobgdb#27]
It is not explained and it is not clear to me when and how to use the F = FILE command

**Comment by marcsosduma** [comment]
In the "resources" directory, we have these examples:

* sample.cbl
* subsample.cbl
* subsubsample.cbl

Execute:
cobgdb sample.cbl subsample.cbl subsubsample.cbl

Now it's possible, for instance, to set a breakpoint in "subsubsample.cbl.". Disable the initial breakpoint, type "f," and select "subsubsample.cbl":

![image](https://github.com/marcsosduma/cobgdb/assets/31162117/d2c51b1e-a9a5-4074-b379-2e380eb0e5c3)

Set a breakpoint at line 14:
![image](https://github.com/marcsosduma/cobgdb/assets/31162117/9c4ba11a-1c76-47ab-8e39-2ffa64df3f60)

Type "R" to run the program and "S" to continue debugging.

**Comment by eugeniodilo** [comment]
Ok Very clear thank you, but now I have a question. 

I have two programs that I compile separately like:
a. GC01BOX.COB which I compile as GC01BOX.DLL
b. GC01BOXDEMO.COB which I compile as GC01BOXDEMO.EXE
(both source are at https://sourceforge.net/p/gnucobol/contrib/HEAD/tree/trunk/tools/TUI-TOOLS/)

The GC01BOXDEMO.EXE program executes a call to GC01BOX.DLL.
How do I run a GC01BOX debug session?

**Comment by marcsosduma** [comment]
Hello Prof. Eugenio!
In my directory, I copied these files:

cobgdb.exe
GC00COLORS.CPY
GC01BOX.COB
GC01BOX.CPY
GC01BOX.dll
GC01BOXDEMO.c
GC01BOXDEMO.c.h
GC01BOXDEMO.c.l.h
GC01BOXDEMO.COB
GC01BOXDEMO.i
GC97KEYCODEGC.CPY
GC98KEYCODE.CPY

I was able to run it in two ways:

Method 1:

cobc -m GC01BOX.COB  -lpdcurses
cobgdb GC01BOXDEMO.COB -lpdcurses

![image](https://github.com/marcsosduma/cobgdb/assets/31162117/703d8e37-dd6c-4b8d-bc51-5945316e186c)

This way, I can debug only the file: GC01BOXDEMO.COB

Method 2:

By passing both programs to `cobgdb` like this:

cobgdb GC01BOXDEMO.COB GC01BOX.COB -lpdcurses

![image](https://github.com/marcsosduma/cobgdb/assets/31162117/4475b27d-bcb9-43ae-9aa0-817d6d48b5dd)

This way, I can debug both COB files.

**Comment by GitMensch** [comment]
I think this issue can be closed, as it was a question (at least when the docs are considered to be good, which may not be the case).

The question raised is _exactly_ what #1 is about, and what prevents both this debugger and the "parent vscode extension" to be used in real-world scenarios. Those commonly consists of thousands of programs, generating and linking them at the same time is just not feasible.

Once the _generation_ and the _run_ is correctly split a user can do:

```sh
cobc -m GC01BOX.COB -lpdcurses -g  # add more options, if needed, -m is not needed as it is the default
cobcgdb GC02BOX.COB -lpdcurses # wrapper, includes all necessary options
cobcgdb -x GC01BOXDEMO.COB    # this time with -x

# start wrapper for the UI and gdb communication, ideally passing everything
# before the filename to GDB as is
cobgdb GC01BOXDEMO

cobgdb -p $runningprocess
```

cobgdb (the "run" part) will then start GDB, execute whatever passed and then use GDB to ask for the source (here GC01BOX.c, GC02BOX.c, GC01BOXDEMO.c) and then do its magic.

**Comment by eugeniodilo** [comment]
> I think this issue can be closed, as it was a question (at least when the docs are considered to be good, which may not be the case).
> 
> The question raised is _exactly_ what #1 is about, and what prevents both this debugger and the "parent vscode extension" to be used in real-world scenarios. Those commonly consists of thousands of programs, generating and linking them at the same time is just not feasible.
> 
> Once the _generation_ and the _run_ is correctly split a user can do:
> 
> ```shell
> cobc -m GC01BOX.COB -lpdcurses -g  # add more options, if needed, -m is not needed as it is the default
> cobcgdb GC02BOX.COB -lpdcurses # wrapper, includes all necessary options
> cobcgdb -x GC01BOXDEMO.COB    # this time with -x
> 
> # start wrapper for the UI and gdb communication, ideally passing everything
> # before the filename to GDB as is
> cobgdb GC01BOXDEMO
> 
> cobgdb -p $runningprocess
> ```
> 
> cobgdb (the "run" part) will then start GDB, execute whatever passed and then use GDB to ask for the source (here GC01BOX.c, GC02BOX.c, GC01BOXDEMO.c) and then do its magic.


sorry but it is not clear what GC02BOX.COB is

**Comment by marcsosduma** [comment]
Hello ! I didn't get a chance to test it... but I believe this would work:
cobc -m subsample.cob 
cobgdb sample.cob subsubsample.cob

**Comment by eugeniodilo** [comment]
FILE informations are ok
