### ISSUE TITLE
FR: Increase the screen size of the DEBUGGER / ANIMATOR window to more than 25x80

### ISSUE THREAD

**Issue by eugeniodilo** [marcsosduma/cobgdb#28]
One improvement that would be really useful would be to be able to have a screen size with more than 25 rows x 80 cols when debugging an application.

When we develop using the ">>SOURCE FREE" option instead of ">>SOURCE FIXED" we can write programs with lines of code longer than the fixed format and therefore more readable and therefore better debuggable code. 
Having more than 80 columns would make debugging much easier.

Having more lines instead of 25 lines would allow to see a larger portions of the code and therefore a better view of the source.

The better solution would be to be able to choose the screen size of the debug window at the user's discretion.
From a minimum of 25x80 to a maximum of 43x132.

Or we could just have a few options, for example
columns 80 or 100 or 132
lines 25 or 35 or 43

Or even just only two possibilities: either 25x80 or 43x120.

Is this something feasible?

**Comment by GitMensch** [comment]
Maybe make that dependent on LINES / COLS variables?

**Comment by marcsosduma** [comment]
Hello! I included the screen resizing handling via the 'w' key, please check if it's OK.

**Comment by eugeniodilo** [comment]
Thank you very much for this great news.
This feature will allow better debugging when using the new FREE FORMAT with lines of code longer than the usual 80 characters.
Unfortunately, however, my test in a Windows 10 environment did not work correctly.
If I type the command "W" the cobgdb window starts flashing without stopping. It would take a little video to show you.
If I type the "W" command again then it goes back to the 80 column format.

**Comment by GitMensch** [comment]
That looks like wincon - @eugeniodilo can you retry with the wiingui port of pdcurses?

**Comment by eugeniodilo** [comment]
Sure and gladly, but could you remind me what exactly I have to do ?

**Comment by GitMensch** [comment]
Get a pdcurses.dll that was built exactly the same as what you have, but with a different port.

If you use Arnold's builds, then that's easy:
* delete pdcurses.dll
* copy pdcurses_wingui.dll to pdcurses.,dll

If I remember correctly Windows prefers dll's from the directory of the application over others, in this case it may be totally enough to copy pdcurses_wingui.dll as pdcurses.dll next to cobgdb.exe

**Comment by eugeniodilo** [comment]
I deleted pdcurses.dll
I copied pdcurses-wingui.dll to pdcurses.dll
Nothing has changed: when using the W command, the cobgdb window with the GnuCOBOL source, instead of switching from the 25 x 80 format to the 34 x \32 format, starts blinking frantically.

**Comment by GitMensch** [comment]
That seems like cobgdb.exe is linked statically to pdcurses wincon port (or does not use curses).

**Comment by eugeniodilo** [comment]
Then we have to ask Marcos for this information !

**Comment by eugeniodilo** [comment]
I managed (I hope) to download a small video.
This is the result when I type the W command


https://github.com/marcsosduma/cobgdb/assets/13390725/df1432cd-2076-42d2-857a-6917d1764030

**Comment by marcsosduma** [comment]
Hi Prof. Eugenio! This is happening because you're using a font that's too large and the system can't increase the window size, please try using a smaller font.

**Comment by marcsosduma** [comment]
Hi Prof. Eugenio! Ok. I'll update the document in the project. Thank you.

**Comment by eugeniodilo** [comment]
completed

**Comment by eugeniodilo** [comment]
Attached [Uploading COBGDB-GnuCOBOL-DEBUGGER-V06-20240505.odt…]() the new version of the user manual

**Comment by GitMensch** [comment]
How can we start cobgdb in wide mode?

Note: I'd personally prefer a "vertical" mode - 80x43 as fixed-form programs still come with "more lines shown is better", but currently the only option is to go to a high width if you want more lines to be shown.

Apart from that: @marcsosduma Can you make the initial window width dependent not on "wide set/unset" but on the value of environment values LINES and COLS, if set (using the next smaller size possible - I guess that couldn't be dynamic to any size, can it)?
