### ISSUE TITLE
FR: Automatic initial Breakpoint  when DECLARATIVES are present

### ISSUE THREAD

**Issue by eugeniodilo** [marcsosduma/cobgdb#29]
The debug / animator session currently automatically creates a BREAKPOINT at the first PROCEDURE DIVISION statement.
If the program has DECLARATIVES (which must necessarily be positioned at the beginning of the PROCEDURE DIVISION) then the automatic BREAKPOINT is positioned at the first statement after the DECLARATIVES which is not the first statement that will be executed by the program. See a sample at following figure.

![DECLARATIVES-01](https://github.com/marcsosduma/cobgdb/assets/13390725/20331ed6-3756-4c4e-9ee3-6f47f8efe494)

In cases like this the automatic BREAKPOINT should be set to the first statement after the END DECLARATIVES.
This is in fact the first statement that will be executed by the program. See following figure.

![DECLARATIVES-02](https://github.com/marcsosduma/cobgdb/assets/13390725/f712ec58-19ab-4fc3-aa94-ac6c08c86b15)

If it can be useful for testing, I attach the GnuCOBOL source program with DECLARATIVES (it is a program that allows you to manage a simple master file).
Select 01 ADD function at first use will activate the DECLARATIVES to create the master file.

[MASTER.COB.TXT](https://github.com/marcsosduma/cobgdb/files/13978105/MASTER.COB.TXT)

**Comment by marcsosduma** [comment]
Hello! I made a change to try to fix this issue.

**Comment by eugeniodilo** [comment]
I confirm.
the problem has been fixed.
good job and well done.
This product gets better and better.
