### ISSUE TITLE
Windows Binaries available ?

### ISSUE THREAD

**Issue by eugeniodilo** [marcsosduma/cobgdb#3]
Hi,
just to ask if it is possible for the .exe executable or the executables for windows to be added to this site.
I would like to start using and testing the debugger but avoiding all the work of installing the various components necessary before being able to compile the source code.

**Comment by marcsosduma** [comment]
Prof. Eugenio, I provided the Windows application, however, I would like to emphasize that it is still in an early stage.

**Comment by eugeniodilo** [comment]
Hi, 
thank you for the clarification. Where can I download the Windows executables to start viewing it?

In any case, I believe that you are on the right path: a dedicated GnuCOBOL debugger, not dependent from the IDE, which can display the user TUI screens (those of displays and accepts) in a separate window.
This debugger in the future could eventually become an integral part of the compiler itself and be distributed together with the compiler.

**Comment by marcsosduma** [comment]
I made the executable available within the project itself. I'm not sure if this is the ideal way. File: cobgdb.exe. Location: https://github.com/marcsosduma/cobgdb.

**Comment by eugeniodilo** [comment]
Downloaded cobgdb.exe into the "bin" folder of the GnuCOBOL compiler (same folder where cobc is).
Executing cobgdb gives to me the attached errore message
![cobgdb](https://github.com/marcsosduma/cobgdb/assets/13390725/43d86a8f-bcbe-423e-a6d5-82bc279c89c5)

PS. may be it should be better to have a new folder into github for saving cobgdb.exe  and other needed files). 
Or may be I saw Arnold Trembley  is used to create a downloadable .zip file.

**Comment by marcsosduma** [comment]
Hello! I'm trying to include the regex library statically, but if you'd like to test it for now, please download the libgnurx-0.dll file as well.

**Comment by marcsosduma** [comment]
mingw com regex como gerar o código com gcc

**Comment by marcsosduma** [comment]
Prof. Eugenio, it seems I managed to build cobgdb with the libgnurx library statically.

**Comment by GitMensch** [comment]
Well done.

I'd suggest to not create the binary before the commit and include it in the repository, but instead use CI/CD (like GitHub Actions or Appveyor) to build the executable and provide an "artifact".
This keeps the repo small and ensures the binary is always created, also if someone else provides a change to be integrated.
