### ISSUE TITLE
BUG: Run command does not work correctly

### ISSUE THREAD

**Issue by eugeniodilo** [marcsosduma/cobgdb#30]
I have encountered a problem which I will try to describe.

I run cobgdb on program customer.cob
The system displays the first statement with a breakpoint (B) at line 103 

I click on Run.
The system execute the Run command =  opens a DOS window and places the symbol (>) next to (B) at line 103.

Now I set another breakpoint at any other point.
for example on line 116.

![BUG10](https://github.com/marcsosduma/cobgdb/assets/13390725/f9726e60-1567-48bf-8f24-99b0bc47a63a)

I click on command Step 2 times.   All is ok.
I click on command  Run to run the program until the next Breakpoint (which would be the new one just inserted at line 116).
The system reopens the DOS window and mistakenly repositions itself on the first Breakpoint al line 103 ?!?!?

**Comment by GitMensch** [comment]
That may be a documentation issue. GDB (which is used here) has:

* `start args` start the program args as parameters and stop at its first instruction
* `start` start the program with the current parameters and stop at its first instruction
* `continue` execute until event (breakpoint, process end, ...), program must already be started
* `run args` start the program args as parameters and continue
* `run` start the program with the current parameters and continue

for `run` and `start` see https://sourceware.org/gdb/current/onlinedocs/gdb.html/Running.html
for the others see https://sourceware.org/gdb/current/onlinedocs/gdb.html/Stopping.html

In any case we should stay at the GDB terms and NOT use the ones that other debuggers may use (its the docs that should specify what that is and another doc may be used to provide a "mapping")

**Comment by eugeniodilo** [comment]
Then I think a clarification on the purpose of the "Run" command is necessary.
Can (must) be used only once and only at the beginning of the debug session?
To go towards the next Breakpoint we already have the "Go" command but this command could also stop the execution in other cases (this also requires a more detailed explanation, perhaps with an example).

**Comment by GitMensch** [comment]
`run` is also quite useful when you want to start debugging from the start - with all breakpoints and other configuration still active.

**Comment by marcsosduma** [comment]
Hello! To run the program up to the cursor position, place the cursor on the desired line and press the "G" key. It's also possible to use the "J" key and provide the line number afterwards.

**Comment by eugeniodilo** [comment]
ok this is clear.

My point concerns the "Run" command. The Help description is now as follows:
R - Run: runs the program until a breakpoint is encountered.

It would be clearer if it were as follows:
R - Run: runs the program from the first statement until a breakpoint is encountered.

Did i write it correctly ?
if so, then the Help message should be modified.

**Comment by GitMensch** [comment]
Possibly even more detailed:_
**R - Run: start a new process and continue until a breakpoint is encountered.**

Note @marcsosduma: cobgdb may want to check the process' state and if the program is active ask the user if that's what he want to do (similar like gdb does on the command line).

**Comment by eugeniodilo** [comment]
Ok but frankly I don't think it's clear anymore.
The word "process" is very generic and lends itself to various interpretations. 
I prefer simpler, direct and non-interpretable explanations like:
**R - Run: runs the program from the first statement until a breakpoint is encountered.**
a confirmation request to the user, not the first time but only if the program is already running, is certainly very useful.

**Comment by GitMensch** [comment]
Many people will think of "program" as of `PROGRAM-ID` - but if you are on the 7th sub-program or not: GDB's `run` will kill the process if there's still one existing and start the complete operating system process again. It will get a new PID (but, if the system settings don't forbid that, the same address space as the running one).

**Comment by marcsosduma** [comment]
Hello! Please, check if the implementation is appropriate.

**Comment by eugeniodilo** [comment]
I would suggest two small adjustments.

1. 
The message:
**Would you like to run the program again?** 
I would write it as follows:
**Would you like to "Run" the program again ? (= Restart)**

2. 
If you left click with mouse on "No" at the Yes / No question, (when cursor was at line 115 see image)
![NO10](https://github.com/marcsosduma/cobgdb/assets/13390725/3381285e-6103-453b-9d63-ffd707117d8d)

then the cursor also moves to the COBOL source line that was underneath the No that was clicked (the line 110 see image)
![NO20](https://github.com/marcsosduma/cobgdb/assets/13390725/dc5a524b-927d-4dce-9409-97fa81b2ad3e)

This shouldn't happen. 
The cursor on the COBOL source should remain on the line where it was before the Yes / No message (line 115).

**Comment by marcsosduma** [comment]
Hello! Please, check if the implementation is appropriate.

**Comment by eugeniodilo** [comment]
This point is solved. Thanks a lot to Marcos.

**Comment by eugeniodilo** [comment]
fixed
