### ISSUE TITLE
FR: An improvement to the function that allows to Change the value of variables

### ISSUE THREAD

**Issue by eugeniodilo** [marcsosduma/cobgdb#32]
DESCRIPTION OF THE PROBLEM.

STEP 1. In the following screen, I type the command V (variables)

![VAR010](https://github.com/marcsosduma/cobgdb/assets/13390725/48b32f6c-3a01-4487-8a84-483025b298ad)

STEP 2. I get the following screen.
I open the WS-MODULE variable and get its fields.
I go with cursor on WS-OP filed and type the  "C" Change  command

![VAR020](https://github.com/marcsosduma/cobgdb/assets/13390725/587406f2-426f-4494-bf95-0735bf66919d)

STEP 3. COBGDB displays the following pop-up with the field already changed and filled whit spaces
![VAR030](https://github.com/marcsosduma/cobgdb/assets/13390725/695c1f0b-71fe-40fd-8c8c-4b47a9c69df5)

STEP 4. At this point, if I exit without doing anything, I will have the variable fixed with all spaces !
See following screenshot.
![VAR040](https://github.com/marcsosduma/cobgdb/assets/13390725/9fc58e7b-0899-48de-87ac-e01db70c0bcd)

SOLUTION 
Once the pop-up window has been displayed (see previous STEP 3) with variable filled with all spaces, it is currently no longer possible to exit without  modifying the variable.

As a solution I would suggest doing the following.

a. display the variable content in the pop-up (see STEP 3) not already at all spaces but with its current value.

b. If I want to modify the variable then I modify (overwrite) it and press ENTER. (this would also allow to modify just a part of the variable - even just one character - without having to rewrite it all)

c if I change my mind and exit without doing anything (please also enable the ESC key which is now not active in the pop-up) or even if I just press ENTER then the value of the variable remains unchanged.

**Comment by GitMensch** [comment]
I totally agree here.

a related FR which may be handled separately: if pressing `=` or `C` while the cursor is over `WS-OP`: directly show the change window

**Comment by eugeniodilo** [comment]
> I totally agree here.
> a related FR which may be handled separately: if pressing `=` or `C` while the cursor is over `WS-OP`: directly show the change window

Ok ... this your FR is the same as  ==>  **FR new command: E - edit variable #5**

**Comment by marcsosduma** [comment]
Hello! Please, see if I'm on the right track. Regarding editing variables using the "E" key, I haven't started the implementation yet

**Comment by eugeniodilo** [comment]
Hi Marcos, 
I tested the improvements to the "Change" feature you released,  I'd say it's just as it should be.  
I would like to point out that when you enter to Change the variable, in the pop-up window, you can delete the values overwriting characters with the SPACE key but you cannot use the CANC and BACKSPACE keys.
If I use them I get some dots: 

![image](https://github.com/marcsosduma/cobgdb/assets/13390725/6117210c-093d-4a44-9749-7f9198448b85)

It's not a big deal but I'll point it out to you.
I would say that these keys should delete a character (CANC delete a char at Right side from cursor position , Backspace delete a char at Right from the cursor posirion) and fill the variable on the rightmost side with spaces.

As a further improvement, the ESC key should be enabled.
If I'm in the pop-up window, even if I've changed the variable, typing ESC exits and the variable isn't updated.
In the upper frame of the pop-up window you could indicate that:
----- Enter= change; ESC=exit without change ------------

The function "V" could be further improved by using the mouse but for this further proposal I will write another ISSUE.
You are doing a wonderful job !

Regarding editing variables using the "E" key we can manage into the issue n.5.

**Comment by eugeniodilo** [comment]
I saw that now the ESC key has been enabled to exit without making changes to the variable: excellent!
The backspace key deletes the character on the left but does not move the rest of the characters. Ditto for the CANC key.

**Comment by marcsosduma** [comment]
Hi Prof. Eugenio! I was unsure whether I should move the characters when using the backspace due to variables with multiple levels.

**Comment by eugeniodilo** [comment]
I believe that the Change function of a Variable should only be used on elementary fields.
The Change function of a variable must not be used on group fields.

If you want to leave everything free as now and in any case, if the Change function of a variable remains executable even on a group field, then it will be the user's responsibility to pay attention to all the consequences on the fields that are part of the group.

**Comment by GitMensch** [comment]
I agree that the change should be possible anywhere and it is the users responsibility to adjust the data "correct".
To be able to do this after DEL/BACKSP it is important to support insert mode (ideally toggle with INS key between that and overwrite).

**Comment by eugeniodilo** [comment]
SOLVED
