### ISSUE TITLE
BUG: using mouse wheel on Variable field

### ISSUE THREAD

**Issue by eugeniodilo** [marcsosduma/cobgdb#34]
When you enter into the Change window of a variable, 
using the mouse wheel back and forth sets strange characters in the field.
See following sample:

![image](https://github.com/marcsosduma/cobgdb/assets/13390725/f18388a4-5b5c-465a-b4ef-6b2a5289c3d1)

**Comment by marcsosduma** [comment]
Hi! I believe I managed to correct it.

**Comment by eugeniodilo** [comment]
fixed
