### ISSUE TITLE
FR: COBGDB user manual

### ISSUE THREAD

**Issue by eugeniodilo** [marcsosduma/cobgdb#36]
I attach the updated version 03 of the COBGDB user manual.
It would be useful to create a "doc" folder in this git repository and save the document in this folder.
[COBGDB-GnuCOBOL-DEBUGGER-V03-20240220.odt](https://github.com/marcsosduma/cobgdb/files/14342901/COBGDB-GnuCOBOL-DEBUGGER-V03-20240220.odt)

**Comment by marcsosduma** [comment]
Hi! Great job Prof. Eugenio!

**Comment by eugeniodilo** [comment]
Thanks Marcos.
I believe that good documentation is absolutely fundamental and very important to maximize the potential of a product and spread its use.
Great job to you for what you have done and for the improvements you are adding.
I would like to contribute more and more directly to the development but unfortunately I don't have the necessary C skills.
Please continue to take care of this development which covers a gap in GnuCOBOL that had become unbearable even compared to other COBOL compiler solutions on the market.

**Comment by eugeniodilo** [comment]
Completed
