### ISSUE TITLE
Suspected virus while downloading

### ISSUE THREAD

**Issue by eugeniodilo** [marcsosduma/cobgdb#37]
I'm trying to download the new version from git but I get an error like there is a virus.

![image](https://github.com/marcsosduma/cobgdb/assets/13390725/f9452536-082c-46f6-9390-3488eae5aa7f)

![image](https://github.com/marcsosduma/cobgdb/assets/13390725/972eed85-0c6a-4188-95f2-e7f7480b1ff5)

I'm not sure it's a real threat.
Can anyone give an opinion?
Can we find a safe way to download a cobgdb.exe executable?

**Comment by eugeniodilo** [comment]
I tried again today and the download of .zip gave me no problems. I don't know what has changed...

**Comment by GitMensch** [comment]
Most likely: the heuristic data of your security suite.

Note that you don't need to download the zip file. As you commonly want to update it would be most reasonable to use a "git clone" once, then "git pull" to update (also has the benefit that you have previous versions available with git commands, if needed).
If you still want to not use git, then you can go to the .exe file and click on "raw" to directly download it.

Also note that I plan to add a github action to create the executable on each commit (this provides you with an "artifact" to download, both for GNU/Linux and Win32, both as 64 bit) and remove it from git, if Marcos doesn't say that he wants to keep it in git for some reason.
