### ISSUE TITLE
cobgdb first look and second run error

### ISSUE THREAD

**Issue by eugeniodilo** [marcsosduma/cobgdb#4]
I managed to start a debug session.
the command I used is the following
cobgdb customer.cob -x -Tlista.txt
The system compiles the program and immediately starts the debugging session. See first attached screenshot.
Unfortunately the Step command doesn't work (it does nothing).
Only the V command which displays a list of some variables works (partially).

Starting from the second execution of the command:
cobgdb customer.cob -x -Tlista.txt
I get the error of the second screenshot.
At this point I can no longer run the debugger.

[
![COBGDB10](https://github.com/marcsosduma/cobgdb/assets/13390725/f1ef49bf-40fb-4e90-8972-11f14457f67c)
![cobgdbERR10](https://github.com/marcsosduma/cobgdb/assets/13390725/7442bf73-4416-4dfe-9178-509def4288c9)
](url)

**Comment by eugeniodilo** [comment]
If it helps you, at this link you will find an example of a debugging session using microfocus COBOL ANIMATOR.

https://www.youtube.com/watch?v=nGgh26Vg_1s

**Comment by marcsosduma** [comment]
Hello, Prof. Eugenio!

Can you take a test?

Execute the command: cobgdb customer.cob
Use the arrows to position the highlighted line, for example, on line 116, like this:
![image](https://github.com/marcsosduma/cobgdb/assets/31162117/6c4cfbb8-ee92-4deb-b367-bc5c020c5d98)

Type "B" to create a breakpoint and "R" for the system to run the application.
![image](https://github.com/marcsosduma/cobgdb/assets/31162117/f42c282b-ebb6-43d4-a915-d03e781ea191)

From that moment on, you can use the keys "S," "N," and "G" to debug the application.

The 'H' key allows you to view the variables on the highlighted line.

![image](https://github.com/marcsosduma/cobgdb/assets/31162117/1a4b2ace-9bcb-48e3-ac50-89e8741cb641)

**Comment by marcsosduma** [comment]
Note: The application will run in a separate window. The 'Accept' command switches the focus between windows. In other words, after entering information via 'Accept,' it is necessary to click on the 'cobgdb' window to continue debugging.

**Comment by eugeniodilo** [comment]
I'm sorry but I can no longer run the application. I get the error I reported in my previous post

**Comment by eugeniodilo** [comment]
Hi Marcos, I'm very sorry to bore you but I can't run the debugger anymore.
I even restarted the computer but I still get the same error. see screenshot of my previous post.
The message I get when using cobgdb says gdb.exe cannot be run.
If I run gdb.exe manually it works normally and its prompt (gdb) appears.
A strange thing is the following.
From windows I start opening a DOS session from windows with the "cmd" command.
then I run cobgdb with all its parameters on the customer.cob program.
The system performs various steps and I see the various cobc compiler messages but then issues the error message and finally **closes the DOS window ?!?!.**
I can't wait to test the debugger but for now I'm stuck and don't know how to fix it. 
do you have any idea ?

**Comment by marcsosduma** [comment]
Hello Prof. Eugenio! Have you tried running cobgdb with just the name of the COBOL program? Like this: 
`cobgdb customer.cob`

**Comment by eugeniodilo** [comment]
I tried running cobgdb customer.cob
but I get the same result and error message.

However if I use gdb alone it works fine. I run:
gdb
(gdb) file customer.exe 
(gdb) run
(gdb) b main
(gdb) s
...etc and the system debugs the C source correctly

**Comment by eugeniodilo** [comment]
Hi again, can you add some documentation and description of the logic and algorithm of the solution you created ?
If I understand correctly, you have developed something like a program that acts as a "front-end" and uses the gdb debugging functions.
In that case do you think it would be possible to develop the same "front-end" functionality in a TUI program written in GnuCOBOL ?

**Comment by marcsosduma** [comment]
Hello, Prof. Eugenio!
I don't have documentation yet, but in general, I'm trying to convert the extension code for VSCODE written by Oleg Kunitsyn, which can be found on GitHub: https://github.com/OlegKunitsyn/gnucobol-debug. I'm attempting to do this in C without using external modules, such as ncurses, for example.

Regarding writing something similar in GnuCOBOL, I think it's possible, but it may be necessary to use code from other languages. It might be necessary to use Python to integrate the application with GDB, for instance.

**Comment by marcsosduma** [comment]
Prof. Eugenio! Would it be something like this?

![image](https://github.com/marcsosduma/cobgdb/assets/31162117/bdb739a9-e5d2-49b2-b469-2f4028c01b5a)

**Comment by eugeniodilo** [comment]
Yes Marcos just like this . great job, well done  !
I think more and more that this could be the debugger to add to the entire
compiler suite.

Il giorno mer 22 nov 2023 alle ore 22:55 MARCOS MARTINS DUMA <
***@***.***> ha scritto:

**Comment by eugeniodilo** [comment]
Hi Marcos,
I started testing again with the most recent version.
with the cursor I position myself on line 116
I insert a B (breakpoint) on line 116.
(when a DEBUG session starts the system should always automatically position itself on the first PROCEDURE DIVISION statement).
then I type S.
the system displays the application screen for selecting a menu item.
I type choice = X (exit)
I go back to the debugger but the system no longer accepts any commands.
am I doing something wrong ?

![image](https://github.com/marcsosduma/cobgdb/assets/13390725/9b3861c2-b14b-4ff1-b8b7-757ce50a5efb)

**Comment by marcsosduma** [comment]
![image](https://github.com/marcsosduma/cobgdb/assets/31162117/2d308810-b0d9-425f-9d9e-df97f4a763e3)
Hi Prof. Eugenio! Could you provide more information about your environment? I'm having trouble reproducing it. Have you tried placing the breakpoint on a previous line?

**Comment by eugeniodilo** [comment]
Hi Marcos, with new version of cobgdb the problem seems it is disappeared. Please close this ISSUE.
