### ISSUE TITLE
User Manual Update

### ISSUE THREAD

**Issue by eugeniodilo** [marcsosduma/cobgdb#40]
Attached user manual new version . Added new -exe option.
Please upload it into GIT repository.

[COBGDB-GnuCOBOL-DEBUGGER-V06-20240505.odt](https://github.com/marcsosduma/cobgdb/files/15245081/COBGDB-GnuCOBOL-DEBUGGER-V06-20240505.odt)

**Comment by marcsosduma** [comment]
Hi Prof. Eugenio! The manual has been updated. Thank you very much.

**Comment by eugeniodilo** [comment]
done
