### ISSUE TITLE
User capability to change screen colors

### ISSUE THREAD

**Issue by Harry6598** [marcsosduma/cobgdb#42]
Hello

Is there a way for a user to change the screen colors used by Cobgdb? 

For example, Cobgdb uses dark blue for some COBOL verbs. I find it hard to read dark blue characters against a black background on my monitor. I would like to change dark blue to light blue. 

Thanks

**Comment by marcsosduma** [comment]
Hi! We haven't implemented a feature to configure the colors yet. But if you want to change it manually, you can modify line 169 of the highlight.c file:
From:
`h->color=color_blue;`
To:
`h->color=color_light_blue;`

**Comment by Harry6598** [comment]
Hello
 In highlight.c I changed line 169 from color_blue to color_light_blue. I ran a test but the characters on the cobgdb screen which had been dark blue did not change. 
Is there something else I need to do along with editing highlight.c in order to make the color change take effect? 
Thanks

**Comment by GitMensch** [comment]
Just to make sure... after you did edit that file and run 'make' you did see that the C compiler did create a new object for which was then used to link cobgdb, right?

**Comment by eugeniodilo** [comment]
done
