### ISSUE TITLE
FR: J -> Jump to line

### ISSUE THREAD

**Issue by GitMensch** [marcsosduma/cobgdb#8]
We already have "run to selected line" (C), which is often useful.

Especially if you recognized that there was an issue with a condition and want to jump into (or out of) its statenents, or when you want to do a missed CALL again (for example because you've used "N"ext instead of "S"tep an additional "J"ump to is very useful.

**Comment by marcsosduma** [comment]
Jump -> Well thought out. I'll take care of it.

**Comment by marcsosduma** [comment]
Hi! I believe I managed to implement it....
